# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main  # Add the main branch here

pool:
  vmImage: 'your-self-hosted-agent'

steps:
  - script: |
      # Merge the feature branch into the main branch
      git checkout main
      git merge --no-ff feature/your-feature-branch
      git push origin main
    displayName: 'Merge feature branch into main and push changes'
